version: "3.9"
services:
  database:
    container_name: roach1
    image: cockroachdb/cockroach:v21.2.3
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - roach_data:/var/lib/postgresql/data
  gateway:
    build: ./gateway/
    ports:
      - "80:80"
  file_service1:
    build: ./service/file_service
    environment:
      - PORT=3050
    ports:
      - "3050:3050"
  file_service2:
    build: ./service/file_service
    environment:
      - PORT=3051
    ports:
      - "3051:3051"
  file_service3:
    build: ./service/file_service
    environment:
      - PORT=3052
    ports:
      - "3052:3052"
  user_service:
    build: ./service/user_service
    ports:
      - "8084:8084"

volumes:
  roach_data: