version: "3.9"
services:
  redis:
    image: "redis:alpine"
#    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
#    networks:
#      node_net:
#        ipv4_address: 172.28.1.4
  database:
    container_name: roach1
    image: cockroachdb/cockroach:v21.2.3
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - roach_data:/var/lib/postgresql/data
  gateway:
    build: ./gateway/
    ports:
      - "80:80"
  file_service1:
    build: ./service/file_service
    environment:
      - PORT=3050
    ports:
      - "3050:3050"
  file_service2:
    build: ./service/file_service
    environment:
      - PORT=3051
    ports:
      - "3051:3051"
  file_service3:
    build: ./service/file_service
    environment:
      - PORT=3052
    ports:
      - "3052:3052"
  user_service:
    build: ./service/user_service
    ports:
      - "8084:8084"

# networking for the Redis container
#networks:
#  node_net:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.0.0/16
volumes:
  roach_data: